# This configuration supports both internal and external keyboards with key mappings applied via `macOS` keyboard settings.
#
# EXPECTED KEYBOARD LAYOUT:
#   - Apple Internal Keyboard/Trackpad:
#     - Globe → Command
#     - Control → Option
#     - Option → Control
#   - Non-Apple Bluetooth Keyboard:
#     - Control → Command
#     - Command → Control
#
# SPECIAL KEY MAPPINGS:
#   - Section Sign → Tilde
#   - Right Shift → Delete
#

# Start `Aerospace` at login.
start-at-login = true

# Enable normalization.
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Disable accordion padding.
accordion-padding = 0

# Set tiles layout as default.
default-root-container-layout = 'tiles'

# Set orientation according to monitor aspect ratio.
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes.
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Automatically re-appear hidden apps on `macOS`.
automatically-unhide-macos-hidden-apps = false

# Floating windows.
[[on-window-detected]]
if.app-name-regex-substring = 'finder'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'wezterm'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'settings'
run = 'layout floating'

# Set key mapping preset.
[key-mapping]
preset = 'qwerty'

# Gaps between each window.
[gaps]
inner.horizontal = 5
inner.vertical = 5
outer.left = 5
outer.bottom = 5
outer.top = 5
outer.right = 5

# 'main' binding mode declaration.
[mode.main.binding]

# Layout floating/tiling toggle.
alt-shift-t = 'layout floating tiling'

# Toggle fullscreen.
alt-shift-f = 'fullscreen'

# Join windows together.
alt-shift-up = 'join-with up'
alt-shift-down = 'join-with down'
alt-shift-left = 'join-with left'
alt-shift-right = 'join-with right'

# Rotate windows.
alt-r = 'layout tiles horizontal vertical'

# Focus navigation.
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Move windows.
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Resize focused window.
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# Workspace management.
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

# Move window to specific workspace.
alt-shift-1 = 'move-node-to-workspace 1 --focus-follows-window'
alt-shift-2 = 'move-node-to-workspace 2 --focus-follows-window'
alt-shift-3 = 'move-node-to-workspace 3 --focus-follows-window'
alt-shift-4 = 'move-node-to-workspace 4 --focus-follows-window'
alt-shift-5 = 'move-node-to-workspace 5 --focus-follows-window'
alt-shift-6 = 'move-node-to-workspace 6 --focus-follows-window'
alt-shift-7 = 'move-node-to-workspace 7 --focus-follows-window'
alt-shift-8 = 'move-node-to-workspace 8 --focus-follows-window'
alt-shift-9 = 'move-node-to-workspace 9 --focus-follows-window'
alt-shift-0 = 'move-node-to-workspace 10 --focus-follows-window'

# Change workspace and focus it.
alt-right = 'workspace next'
alt-left = 'workspace prev'

# Move workspace to next monitor.
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# TODO: Cycle through active windows/applications using `OPT+Tab` (internal) or `ALT+Tab` (external).

# Enter service mode.
alt-semicolon = 'mode service'

# Language switch.
cmd-space = 'exec-and-forget osascript ~/.config/scripts/switch_input_source.scpt'

# Spotlight trigger script.
cmd-period = 'exec-and-forget ~/.config/scripts/open_spotlight.sh'

# Applications.
cmd-b = 'exec-and-forget open -a "/Applications/Google Chrome.app"'

cmd-e = 'exec-and-forget open -a "/Applications/Visual Studio Code.app"'

cmd-i = 'exec-and-forget open --background -a Docker'

cmd-backtick = 'exec-and-forget open -a Finder'

cmd-m = 'exec-and-forget open -a /Applications/Spotify.app'

cmd-k = 'exec-and-forget open -a /Applications/Obsidian.app'

cmd-quote = 'exec-and-forget open -a "/System/Applications/System Settings.app"'

cmd-slash = 'exec-and-forget open -a "/Applications/Perplexity.app"'

cmd-semicolon = 'exec-and-forget osascript ~/.config/scripts/open_wezterm.scpt'

# Lock screen.
cmd-backslash = 'exec-and-forget ~/.config/scripts/lock_screen.sh'

# Screen recording.
cmd-shift-b = 'exec-and-forget open -a Screenshot'

# TODO: Add keybindings to trigger system shutdown (SUPER + Esc) and restart (SUPER + Right square bracket).

# 'service' binding mode declaration.
[mode.service.binding]

# After entering service mode, press R to reload environment (configuration, workspace tree, and workspaces), then return to the main mode.
r = ['exec-and-forget ~/.config/scripts/reload_environment.sh', 'mode main']

# After entering service mode, press Backspace to close all windows except the current one.
backspace = ['close-all-windows-but-current', 'mode main']
